---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        env: # список env переменных, к-ые будут созданы в контейнере
        # Минус - нужно в каждом деплое дублировать переменные, если, например, они для авторизации и они одинаковые
        # Поэтьому лучше использовать ConfigMap, в котором хранятся env
        - name: TEST # Ключ 
          value: foo # Значение
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
...
